#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDLpakse
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EDLpakse")]
	public partial class EDLpakseDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertT_Activity(T_Activity instance);
    partial void UpdateT_Activity(T_Activity instance);
    partial void DeleteT_Activity(T_Activity instance);
    partial void InsertT_Auth(T_Auth instance);
    partial void UpdateT_Auth(T_Auth instance);
    partial void DeleteT_Auth(T_Auth instance);
    partial void InsertT_Country(T_Country instance);
    partial void UpdateT_Country(T_Country instance);
    partial void DeleteT_Country(T_Country instance);
    partial void InsertT_Culture(T_Culture instance);
    partial void UpdateT_Culture(T_Culture instance);
    partial void DeleteT_Culture(T_Culture instance);
    partial void InsertT_Department(T_Department instance);
    partial void UpdateT_Department(T_Department instance);
    partial void DeleteT_Department(T_Department instance);
    partial void InsertT_Education(T_Education instance);
    partial void UpdateT_Education(T_Education instance);
    partial void DeleteT_Education(T_Education instance);
    partial void InsertT_Employee(T_Employee instance);
    partial void UpdateT_Employee(T_Employee instance);
    partial void DeleteT_Employee(T_Employee instance);
    partial void InsertT_Kind_staff(T_Kind_staff instance);
    partial void UpdateT_Kind_staff(T_Kind_staff instance);
    partial void DeleteT_Kind_staff(T_Kind_staff instance);
    partial void InsertT_Position(T_Position instance);
    partial void UpdateT_Position(T_Position instance);
    partial void DeleteT_Position(T_Position instance);
    partial void InsertT_Title(T_Title instance);
    partial void UpdateT_Title(T_Title instance);
    partial void DeleteT_Title(T_Title instance);
    partial void InsertT_Unit(T_Unit instance);
    partial void UpdateT_Unit(T_Unit instance);
    partial void DeleteT_Unit(T_Unit instance);
    partial void InsertT_Vacation_Info(T_Vacation_Info instance);
    partial void UpdateT_Vacation_Info(T_Vacation_Info instance);
    partial void DeleteT_Vacation_Info(T_Vacation_Info instance);
    partial void InsertT_Participate(T_Participate instance);
    partial void UpdateT_Participate(T_Participate instance);
    partial void DeleteT_Participate(T_Participate instance);
    #endregion
		
		public EDLpakseDataClassesDataContext() : 
				base(global::EDLpakse.Properties.Settings.Default.EDLpakseConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public EDLpakseDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EDLpakseDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EDLpakseDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EDLpakseDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<T_Activity> T_Activities
		{
			get
			{
				return this.GetTable<T_Activity>();
			}
		}
		
		public System.Data.Linq.Table<T_Auth> T_Auths
		{
			get
			{
				return this.GetTable<T_Auth>();
			}
		}
		
		public System.Data.Linq.Table<T_Country> T_Countries
		{
			get
			{
				return this.GetTable<T_Country>();
			}
		}
		
		public System.Data.Linq.Table<T_Culture> T_Cultures
		{
			get
			{
				return this.GetTable<T_Culture>();
			}
		}
		
		public System.Data.Linq.Table<T_Department> T_Departments
		{
			get
			{
				return this.GetTable<T_Department>();
			}
		}
		
		public System.Data.Linq.Table<T_Education> T_Educations
		{
			get
			{
				return this.GetTable<T_Education>();
			}
		}
		
		public System.Data.Linq.Table<T_Employee> T_Employees
		{
			get
			{
				return this.GetTable<T_Employee>();
			}
		}
		
		public System.Data.Linq.Table<T_Kind_staff> T_Kind_staffs
		{
			get
			{
				return this.GetTable<T_Kind_staff>();
			}
		}
		
		public System.Data.Linq.Table<T_Position> T_Positions
		{
			get
			{
				return this.GetTable<T_Position>();
			}
		}
		
		public System.Data.Linq.Table<T_Title> T_Titles
		{
			get
			{
				return this.GetTable<T_Title>();
			}
		}
		
		public System.Data.Linq.Table<T_Unit> T_Units
		{
			get
			{
				return this.GetTable<T_Unit>();
			}
		}
		
		public System.Data.Linq.Table<T_Vacation_Info> T_Vacation_Infos
		{
			get
			{
				return this.GetTable<T_Vacation_Info>();
			}
		}
		
		public System.Data.Linq.Table<T_Participate> T_Participates
		{
			get
			{
				return this.GetTable<T_Participate>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Activity")]
	public partial class T_Activity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Activity_ID;
		
		private string _Activity;
		
		private string _Activity_When;
		
		private string _Activity_End;
		
		private string _Activity_Detail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnActivity_IDChanging(decimal value);
    partial void OnActivity_IDChanged();
    partial void OnActivityChanging(string value);
    partial void OnActivityChanged();
    partial void OnActivity_WhenChanging(string value);
    partial void OnActivity_WhenChanged();
    partial void OnActivity_EndChanging(string value);
    partial void OnActivity_EndChanged();
    partial void OnActivity_DetailChanging(string value);
    partial void OnActivity_DetailChanged();
    #endregion
		
		public T_Activity()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activity_ID", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal Activity_ID
		{
			get
			{
				return this._Activity_ID;
			}
			set
			{
				if ((this._Activity_ID != value))
				{
					this.OnActivity_IDChanging(value);
					this.SendPropertyChanging();
					this._Activity_ID = value;
					this.SendPropertyChanged("Activity_ID");
					this.OnActivity_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activity", DbType="NVarChar(50)")]
		public string Activity
		{
			get
			{
				return this._Activity;
			}
			set
			{
				if ((this._Activity != value))
				{
					this.OnActivityChanging(value);
					this.SendPropertyChanging();
					this._Activity = value;
					this.SendPropertyChanged("Activity");
					this.OnActivityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activity_When", DbType="NVarChar(50)")]
		public string Activity_When
		{
			get
			{
				return this._Activity_When;
			}
			set
			{
				if ((this._Activity_When != value))
				{
					this.OnActivity_WhenChanging(value);
					this.SendPropertyChanging();
					this._Activity_When = value;
					this.SendPropertyChanged("Activity_When");
					this.OnActivity_WhenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activity_End", DbType="NVarChar(50)")]
		public string Activity_End
		{
			get
			{
				return this._Activity_End;
			}
			set
			{
				if ((this._Activity_End != value))
				{
					this.OnActivity_EndChanging(value);
					this.SendPropertyChanging();
					this._Activity_End = value;
					this.SendPropertyChanged("Activity_End");
					this.OnActivity_EndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activity_Detail", DbType="NVarChar(50)")]
		public string Activity_Detail
		{
			get
			{
				return this._Activity_Detail;
			}
			set
			{
				if ((this._Activity_Detail != value))
				{
					this.OnActivity_DetailChanging(value);
					this.SendPropertyChanging();
					this._Activity_Detail = value;
					this.SendPropertyChanged("Activity_Detail");
					this.OnActivity_DetailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Auth")]
	public partial class T_Auth : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Index;
		
		private string _User_ID;
		
		private string _User_Passward;
		
		private string _User_Level;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIndexChanging(decimal value);
    partial void OnIndexChanged();
    partial void OnUser_IDChanging(string value);
    partial void OnUser_IDChanged();
    partial void OnUser_PasswardChanging(string value);
    partial void OnUser_PasswardChanged();
    partial void OnUser_LevelChanging(string value);
    partial void OnUser_LevelChanged();
    #endregion
		
		public T_Auth()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Index]", Storage="_Index", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal Index
		{
			get
			{
				return this._Index;
			}
			set
			{
				if ((this._Index != value))
				{
					this.OnIndexChanging(value);
					this.SendPropertyChanging();
					this._Index = value;
					this.SendPropertyChanged("Index");
					this.OnIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="NVarChar(50)")]
		public string User_ID
		{
			get
			{
				return this._User_ID;
			}
			set
			{
				if ((this._User_ID != value))
				{
					this.OnUser_IDChanging(value);
					this.SendPropertyChanging();
					this._User_ID = value;
					this.SendPropertyChanged("User_ID");
					this.OnUser_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Passward", DbType="NVarChar(50)")]
		public string User_Passward
		{
			get
			{
				return this._User_Passward;
			}
			set
			{
				if ((this._User_Passward != value))
				{
					this.OnUser_PasswardChanging(value);
					this.SendPropertyChanging();
					this._User_Passward = value;
					this.SendPropertyChanged("User_Passward");
					this.OnUser_PasswardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Level", DbType="NVarChar(50)")]
		public string User_Level
		{
			get
			{
				return this._User_Level;
			}
			set
			{
				if ((this._User_Level != value))
				{
					this.OnUser_LevelChanging(value);
					this.SendPropertyChanging();
					this._User_Level = value;
					this.SendPropertyChanged("User_Level");
					this.OnUser_LevelChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Country")]
	public partial class T_Country : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Country_ID;
		
		private string _Country;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCountry_IDChanging(decimal value);
    partial void OnCountry_IDChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    #endregion
		
		public T_Country()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country_ID", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal Country_ID
		{
			get
			{
				return this._Country_ID;
			}
			set
			{
				if ((this._Country_ID != value))
				{
					this.OnCountry_IDChanging(value);
					this.SendPropertyChanging();
					this._Country_ID = value;
					this.SendPropertyChanged("Country_ID");
					this.OnCountry_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(50)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Culture")]
	public partial class T_Culture : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Culture_ID;
		
		private string _Culture;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCulture_IDChanging(decimal value);
    partial void OnCulture_IDChanged();
    partial void OnCultureChanging(string value);
    partial void OnCultureChanged();
    #endregion
		
		public T_Culture()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Culture_ID", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal Culture_ID
		{
			get
			{
				return this._Culture_ID;
			}
			set
			{
				if ((this._Culture_ID != value))
				{
					this.OnCulture_IDChanging(value);
					this.SendPropertyChanging();
					this._Culture_ID = value;
					this.SendPropertyChanged("Culture_ID");
					this.OnCulture_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Culture", DbType="NVarChar(50)")]
		public string Culture
		{
			get
			{
				return this._Culture;
			}
			set
			{
				if ((this._Culture != value))
				{
					this.OnCultureChanging(value);
					this.SendPropertyChanging();
					this._Culture = value;
					this.SendPropertyChanged("Culture");
					this.OnCultureChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Department")]
	public partial class T_Department : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Department_ID;
		
		private string _Departmen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDepartment_IDChanging(decimal value);
    partial void OnDepartment_IDChanged();
    partial void OnDepartmenChanging(string value);
    partial void OnDepartmenChanged();
    #endregion
		
		public T_Department()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department_ID", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal Department_ID
		{
			get
			{
				return this._Department_ID;
			}
			set
			{
				if ((this._Department_ID != value))
				{
					this.OnDepartment_IDChanging(value);
					this.SendPropertyChanging();
					this._Department_ID = value;
					this.SendPropertyChanged("Department_ID");
					this.OnDepartment_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departmen", DbType="NVarChar(50)")]
		public string Departmen
		{
			get
			{
				return this._Departmen;
			}
			set
			{
				if ((this._Departmen != value))
				{
					this.OnDepartmenChanging(value);
					this.SendPropertyChanging();
					this._Departmen = value;
					this.SendPropertyChanged("Departmen");
					this.OnDepartmenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Education")]
	public partial class T_Education : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Education_ID;
		
		private string _Education;
		
		private string _Education_Level;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEducation_IDChanging(decimal value);
    partial void OnEducation_IDChanged();
    partial void OnEducationChanging(string value);
    partial void OnEducationChanged();
    partial void OnEducation_LevelChanging(string value);
    partial void OnEducation_LevelChanged();
    #endregion
		
		public T_Education()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Education_ID", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal Education_ID
		{
			get
			{
				return this._Education_ID;
			}
			set
			{
				if ((this._Education_ID != value))
				{
					this.OnEducation_IDChanging(value);
					this.SendPropertyChanging();
					this._Education_ID = value;
					this.SendPropertyChanged("Education_ID");
					this.OnEducation_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Education", DbType="NVarChar(50)")]
		public string Education
		{
			get
			{
				return this._Education;
			}
			set
			{
				if ((this._Education != value))
				{
					this.OnEducationChanging(value);
					this.SendPropertyChanging();
					this._Education = value;
					this.SendPropertyChanged("Education");
					this.OnEducationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Education_Level", DbType="NVarChar(50)")]
		public string Education_Level
		{
			get
			{
				return this._Education_Level;
			}
			set
			{
				if ((this._Education_Level != value))
				{
					this.OnEducation_LevelChanging(value);
					this.SendPropertyChanging();
					this._Education_Level = value;
					this.SendPropertyChanged("Education_Level");
					this.OnEducation_LevelChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Employee")]
	public partial class T_Employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Index;
		
		private System.Nullable<decimal> _Employee_ID;
		
		private System.Nullable<decimal> _Education_ID;
		
		private System.Nullable<decimal> _Culture_ID;
		
		private System.Nullable<decimal> _Staff_ID;
		
		private System.Nullable<decimal> _Position_ID;
		
		private System.Nullable<decimal> _Department_ID;
		
		private System.Nullable<decimal> _Unit_ID;
		
		private System.Nullable<decimal> _Country_ID;
		
		private System.Data.Linq.Binary _Photo;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _WorkExperial;
		
		private string _StartWork_Date;
		
		private string _EndWork_Date;
		
		private string _Vacation;
		
		private System.Nullable<decimal> _Titile_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIndexChanging(decimal value);
    partial void OnIndexChanged();
    partial void OnEmployee_IDChanging(System.Nullable<decimal> value);
    partial void OnEmployee_IDChanged();
    partial void OnEducation_IDChanging(System.Nullable<decimal> value);
    partial void OnEducation_IDChanged();
    partial void OnCulture_IDChanging(System.Nullable<decimal> value);
    partial void OnCulture_IDChanged();
    partial void OnStaff_IDChanging(System.Nullable<decimal> value);
    partial void OnStaff_IDChanged();
    partial void OnPosition_IDChanging(System.Nullable<decimal> value);
    partial void OnPosition_IDChanged();
    partial void OnDepartment_IDChanging(System.Nullable<decimal> value);
    partial void OnDepartment_IDChanged();
    partial void OnUnit_IDChanging(System.Nullable<decimal> value);
    partial void OnUnit_IDChanged();
    partial void OnCountry_IDChanging(System.Nullable<decimal> value);
    partial void OnCountry_IDChanged();
    partial void OnPhotoChanging(System.Data.Linq.Binary value);
    partial void OnPhotoChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnWorkExperialChanging(string value);
    partial void OnWorkExperialChanged();
    partial void OnStartWork_DateChanging(string value);
    partial void OnStartWork_DateChanged();
    partial void OnEndWork_DateChanging(string value);
    partial void OnEndWork_DateChanged();
    partial void OnVacationChanging(string value);
    partial void OnVacationChanged();
    partial void OnTitile_IDChanging(System.Nullable<decimal> value);
    partial void OnTitile_IDChanged();
    #endregion
		
		public T_Employee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Index]", Storage="_Index", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal Index
		{
			get
			{
				return this._Index;
			}
			set
			{
				if ((this._Index != value))
				{
					this.OnIndexChanging(value);
					this.SendPropertyChanging();
					this._Index = value;
					this.SendPropertyChanged("Index");
					this.OnIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employee_ID", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Employee_ID
		{
			get
			{
				return this._Employee_ID;
			}
			set
			{
				if ((this._Employee_ID != value))
				{
					this.OnEmployee_IDChanging(value);
					this.SendPropertyChanging();
					this._Employee_ID = value;
					this.SendPropertyChanged("Employee_ID");
					this.OnEmployee_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Education_ID", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Education_ID
		{
			get
			{
				return this._Education_ID;
			}
			set
			{
				if ((this._Education_ID != value))
				{
					this.OnEducation_IDChanging(value);
					this.SendPropertyChanging();
					this._Education_ID = value;
					this.SendPropertyChanged("Education_ID");
					this.OnEducation_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Culture_ID", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Culture_ID
		{
			get
			{
				return this._Culture_ID;
			}
			set
			{
				if ((this._Culture_ID != value))
				{
					this.OnCulture_IDChanging(value);
					this.SendPropertyChanging();
					this._Culture_ID = value;
					this.SendPropertyChanged("Culture_ID");
					this.OnCulture_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Staff_ID", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Staff_ID
		{
			get
			{
				return this._Staff_ID;
			}
			set
			{
				if ((this._Staff_ID != value))
				{
					this.OnStaff_IDChanging(value);
					this.SendPropertyChanging();
					this._Staff_ID = value;
					this.SendPropertyChanged("Staff_ID");
					this.OnStaff_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position_ID", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Position_ID
		{
			get
			{
				return this._Position_ID;
			}
			set
			{
				if ((this._Position_ID != value))
				{
					this.OnPosition_IDChanging(value);
					this.SendPropertyChanging();
					this._Position_ID = value;
					this.SendPropertyChanged("Position_ID");
					this.OnPosition_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department_ID", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Department_ID
		{
			get
			{
				return this._Department_ID;
			}
			set
			{
				if ((this._Department_ID != value))
				{
					this.OnDepartment_IDChanging(value);
					this.SendPropertyChanging();
					this._Department_ID = value;
					this.SendPropertyChanged("Department_ID");
					this.OnDepartment_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit_ID", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Unit_ID
		{
			get
			{
				return this._Unit_ID;
			}
			set
			{
				if ((this._Unit_ID != value))
				{
					this.OnUnit_IDChanging(value);
					this.SendPropertyChanging();
					this._Unit_ID = value;
					this.SendPropertyChanged("Unit_ID");
					this.OnUnit_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country_ID", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Country_ID
		{
			get
			{
				return this._Country_ID;
			}
			set
			{
				if ((this._Country_ID != value))
				{
					this.OnCountry_IDChanging(value);
					this.SendPropertyChanging();
					this._Country_ID = value;
					this.SendPropertyChanged("Country_ID");
					this.OnCountry_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Photo
		{
			get
			{
				return this._Photo;
			}
			set
			{
				if ((this._Photo != value))
				{
					this.OnPhotoChanging(value);
					this.SendPropertyChanging();
					this._Photo = value;
					this.SendPropertyChanged("Photo");
					this.OnPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkExperial", DbType="NVarChar(50)")]
		public string WorkExperial
		{
			get
			{
				return this._WorkExperial;
			}
			set
			{
				if ((this._WorkExperial != value))
				{
					this.OnWorkExperialChanging(value);
					this.SendPropertyChanging();
					this._WorkExperial = value;
					this.SendPropertyChanged("WorkExperial");
					this.OnWorkExperialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartWork_Date", DbType="NVarChar(50)")]
		public string StartWork_Date
		{
			get
			{
				return this._StartWork_Date;
			}
			set
			{
				if ((this._StartWork_Date != value))
				{
					this.OnStartWork_DateChanging(value);
					this.SendPropertyChanging();
					this._StartWork_Date = value;
					this.SendPropertyChanged("StartWork_Date");
					this.OnStartWork_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndWork_Date", DbType="NVarChar(50)")]
		public string EndWork_Date
		{
			get
			{
				return this._EndWork_Date;
			}
			set
			{
				if ((this._EndWork_Date != value))
				{
					this.OnEndWork_DateChanging(value);
					this.SendPropertyChanging();
					this._EndWork_Date = value;
					this.SendPropertyChanged("EndWork_Date");
					this.OnEndWork_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vacation", DbType="NVarChar(50)")]
		public string Vacation
		{
			get
			{
				return this._Vacation;
			}
			set
			{
				if ((this._Vacation != value))
				{
					this.OnVacationChanging(value);
					this.SendPropertyChanging();
					this._Vacation = value;
					this.SendPropertyChanged("Vacation");
					this.OnVacationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titile_ID", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Titile_ID
		{
			get
			{
				return this._Titile_ID;
			}
			set
			{
				if ((this._Titile_ID != value))
				{
					this.OnTitile_IDChanging(value);
					this.SendPropertyChanging();
					this._Titile_ID = value;
					this.SendPropertyChanged("Titile_ID");
					this.OnTitile_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Kind_staff")]
	public partial class T_Kind_staff : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Staff_ID;
		
		private string _Staff_Kind;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStaff_IDChanging(decimal value);
    partial void OnStaff_IDChanged();
    partial void OnStaff_KindChanging(string value);
    partial void OnStaff_KindChanged();
    #endregion
		
		public T_Kind_staff()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Staff_ID", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal Staff_ID
		{
			get
			{
				return this._Staff_ID;
			}
			set
			{
				if ((this._Staff_ID != value))
				{
					this.OnStaff_IDChanging(value);
					this.SendPropertyChanging();
					this._Staff_ID = value;
					this.SendPropertyChanged("Staff_ID");
					this.OnStaff_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Staff_Kind", DbType="NVarChar(50)")]
		public string Staff_Kind
		{
			get
			{
				return this._Staff_Kind;
			}
			set
			{
				if ((this._Staff_Kind != value))
				{
					this.OnStaff_KindChanging(value);
					this.SendPropertyChanging();
					this._Staff_Kind = value;
					this.SendPropertyChanged("Staff_Kind");
					this.OnStaff_KindChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Position")]
	public partial class T_Position : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Position_ID;
		
		private string _Position;
		
		private string _Position_Salary;
		
		private string _Position_Salary_Old;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPosition_IDChanging(decimal value);
    partial void OnPosition_IDChanged();
    partial void OnPositionChanging(string value);
    partial void OnPositionChanged();
    partial void OnPosition_SalaryChanging(string value);
    partial void OnPosition_SalaryChanged();
    partial void OnPosition_Salary_OldChanging(string value);
    partial void OnPosition_Salary_OldChanged();
    #endregion
		
		public T_Position()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position_ID", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal Position_ID
		{
			get
			{
				return this._Position_ID;
			}
			set
			{
				if ((this._Position_ID != value))
				{
					this.OnPosition_IDChanging(value);
					this.SendPropertyChanging();
					this._Position_ID = value;
					this.SendPropertyChanged("Position_ID");
					this.OnPosition_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="NVarChar(50)")]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this.OnPositionChanging(value);
					this.SendPropertyChanging();
					this._Position = value;
					this.SendPropertyChanged("Position");
					this.OnPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position_Salary", DbType="NVarChar(50)")]
		public string Position_Salary
		{
			get
			{
				return this._Position_Salary;
			}
			set
			{
				if ((this._Position_Salary != value))
				{
					this.OnPosition_SalaryChanging(value);
					this.SendPropertyChanging();
					this._Position_Salary = value;
					this.SendPropertyChanged("Position_Salary");
					this.OnPosition_SalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position_Salary_Old", DbType="NVarChar(50)")]
		public string Position_Salary_Old
		{
			get
			{
				return this._Position_Salary_Old;
			}
			set
			{
				if ((this._Position_Salary_Old != value))
				{
					this.OnPosition_Salary_OldChanging(value);
					this.SendPropertyChanging();
					this._Position_Salary_Old = value;
					this.SendPropertyChanged("Position_Salary_Old");
					this.OnPosition_Salary_OldChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Title")]
	public partial class T_Title : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Title_ID;
		
		private string _Title;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTitle_IDChanging(decimal value);
    partial void OnTitle_IDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    #endregion
		
		public T_Title()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title_ID", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal Title_ID
		{
			get
			{
				return this._Title_ID;
			}
			set
			{
				if ((this._Title_ID != value))
				{
					this.OnTitle_IDChanging(value);
					this.SendPropertyChanging();
					this._Title_ID = value;
					this.SendPropertyChanged("Title_ID");
					this.OnTitle_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(50)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Unit")]
	public partial class T_Unit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Unit_ID;
		
		private string _Unit;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUnit_IDChanging(decimal value);
    partial void OnUnit_IDChanged();
    partial void OnUnitChanging(string value);
    partial void OnUnitChanged();
    #endregion
		
		public T_Unit()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit_ID", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal Unit_ID
		{
			get
			{
				return this._Unit_ID;
			}
			set
			{
				if ((this._Unit_ID != value))
				{
					this.OnUnit_IDChanging(value);
					this.SendPropertyChanging();
					this._Unit_ID = value;
					this.SendPropertyChanged("Unit_ID");
					this.OnUnit_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit", DbType="NVarChar(50)")]
		public string Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this.OnUnitChanging(value);
					this.SendPropertyChanging();
					this._Unit = value;
					this.SendPropertyChanged("Unit");
					this.OnUnitChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Vacation_Info")]
	public partial class T_Vacation_Info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Index;
		
		private System.Nullable<decimal> _Employee_ID;
		
		private string _Vacation_Info;
		
		private string _Vacation_Start;
		
		private string _Vacation_End;
		
		private string _Vacation_Howlong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIndexChanging(decimal value);
    partial void OnIndexChanged();
    partial void OnEmployee_IDChanging(System.Nullable<decimal> value);
    partial void OnEmployee_IDChanged();
    partial void OnVacation_InfoChanging(string value);
    partial void OnVacation_InfoChanged();
    partial void OnVacation_StartChanging(string value);
    partial void OnVacation_StartChanged();
    partial void OnVacation_EndChanging(string value);
    partial void OnVacation_EndChanged();
    partial void OnVacation_HowlongChanging(string value);
    partial void OnVacation_HowlongChanged();
    #endregion
		
		public T_Vacation_Info()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Index]", Storage="_Index", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal Index
		{
			get
			{
				return this._Index;
			}
			set
			{
				if ((this._Index != value))
				{
					this.OnIndexChanging(value);
					this.SendPropertyChanging();
					this._Index = value;
					this.SendPropertyChanged("Index");
					this.OnIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employee_ID", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Employee_ID
		{
			get
			{
				return this._Employee_ID;
			}
			set
			{
				if ((this._Employee_ID != value))
				{
					this.OnEmployee_IDChanging(value);
					this.SendPropertyChanging();
					this._Employee_ID = value;
					this.SendPropertyChanged("Employee_ID");
					this.OnEmployee_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vacation_Info", DbType="NVarChar(50)")]
		public string Vacation_Info
		{
			get
			{
				return this._Vacation_Info;
			}
			set
			{
				if ((this._Vacation_Info != value))
				{
					this.OnVacation_InfoChanging(value);
					this.SendPropertyChanging();
					this._Vacation_Info = value;
					this.SendPropertyChanged("Vacation_Info");
					this.OnVacation_InfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vacation_Start", DbType="NVarChar(50)")]
		public string Vacation_Start
		{
			get
			{
				return this._Vacation_Start;
			}
			set
			{
				if ((this._Vacation_Start != value))
				{
					this.OnVacation_StartChanging(value);
					this.SendPropertyChanging();
					this._Vacation_Start = value;
					this.SendPropertyChanged("Vacation_Start");
					this.OnVacation_StartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vacation_End", DbType="NVarChar(50)")]
		public string Vacation_End
		{
			get
			{
				return this._Vacation_End;
			}
			set
			{
				if ((this._Vacation_End != value))
				{
					this.OnVacation_EndChanging(value);
					this.SendPropertyChanging();
					this._Vacation_End = value;
					this.SendPropertyChanged("Vacation_End");
					this.OnVacation_EndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vacation_Howlong", DbType="NVarChar(50)")]
		public string Vacation_Howlong
		{
			get
			{
				return this._Vacation_Howlong;
			}
			set
			{
				if ((this._Vacation_Howlong != value))
				{
					this.OnVacation_HowlongChanging(value);
					this.SendPropertyChanging();
					this._Vacation_Howlong = value;
					this.SendPropertyChanged("Vacation_Howlong");
					this.OnVacation_HowlongChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Participate")]
	public partial class T_Participate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Index;
		
		private System.Nullable<decimal> _Activity_ID;
		
		private System.Nullable<decimal> _Employee_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIndexChanging(decimal value);
    partial void OnIndexChanged();
    partial void OnActivity_IDChanging(System.Nullable<decimal> value);
    partial void OnActivity_IDChanged();
    partial void OnEmployee_IDChanging(System.Nullable<decimal> value);
    partial void OnEmployee_IDChanged();
    #endregion
		
		public T_Participate()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Index]", Storage="_Index", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal Index
		{
			get
			{
				return this._Index;
			}
			set
			{
				if ((this._Index != value))
				{
					this.OnIndexChanging(value);
					this.SendPropertyChanging();
					this._Index = value;
					this.SendPropertyChanged("Index");
					this.OnIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activity_ID", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Activity_ID
		{
			get
			{
				return this._Activity_ID;
			}
			set
			{
				if ((this._Activity_ID != value))
				{
					this.OnActivity_IDChanging(value);
					this.SendPropertyChanging();
					this._Activity_ID = value;
					this.SendPropertyChanged("Activity_ID");
					this.OnActivity_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employee_ID", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Employee_ID
		{
			get
			{
				return this._Employee_ID;
			}
			set
			{
				if ((this._Employee_ID != value))
				{
					this.OnEmployee_IDChanging(value);
					this.SendPropertyChanging();
					this._Employee_ID = value;
					this.SendPropertyChanged("Employee_ID");
					this.OnEmployee_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
